### ISSUE TITLE
Get total docs in scope query

### ISSUE THREAD

**Issue by senorezi** [Nuix/Search-Module#3]
Hello Jason,

For this app, is it possible to add the number of documents that are in the Scope Query in the Summary page?

Right now it is

Scope Query "tag"
Default Fields {selected fields to search}
Terms ##
Total Hits ##

Is it possible to add Scope Query Item Count underneath Scope Query? Thanks!!

**Comment by JuicyDragon** [comment]
Fixed in commit 36ae894430cff68a7c2d8a0fa26af8c543dd0081

Updated available in release [v3.16.0](https://github.com/Nuix/Search-Module/releases/tag/v3.16.0)
