### ISSUE TITLE
RegEx Patterns

### ISSUE THREAD

**Issue by hsidjflood** [Nuix/Search-Module#6]
When using RegEx Patterns, having anything other than s space or letter after the opening '/' throws an error. For example: /\d{2}/ is seen as an invalid search, but / \d{2}/ is fine.

**Comment by JuicyDragon** [comment]
Hello @hsidjflood , thanks for reporting this.  I've removed some logic in the query validation that is no longer needed and that seems to have fixed things up.  The updated version of the script may be downloaded from here: https://github.com/Nuix/Search-Module/releases/tag/v3.17.0
