### ISSUE TITLE
Trying to run search module on records that are in an exclusion item?

### ISSUE THREAD

**Issue by ccastillo-id** [Nuix/Search-Module#7]
Hello, I have some records that are in exclusion items but when I run this kind of query in the search module, they do not get accounted for in my scope

![image](https://user-images.githubusercontent.com/71530530/118901307-f0f97f00-b8e0-11eb-9af2-17c64c24f476.png)

**Comment by JuicyDragon** [comment]
Hello @ccastillo-id,

The search criteria `has-exclusion:0` is saying "items without an exclusion" (which I suspect you are aware).  Assuming you are seeing excluded items in the results when you expect them not to be present, there is another place that can affect things.

The API (unlike the GUI) does not automatically remove excluded items from results.  As noted in the API documentation for Case.search:

_Searches performed from scripts are not subjected to any filters which the GUI might enable by default, such as exclusions.
To apply these filters, they should be added into the query string._

While a search that includes `has-exclusion:0` shouldn't result in excluded items, methods like ItemUtility.findFamilies, ItemUtility.findDescendants, and so on still can.  To make things behave more like you might expect in the GUI the script does have an option for this on the "Terms" tab:

![image](https://user-images.githubusercontent.com/11775738/119177853-c236f200-ba21-11eb-92f6-038a44a98013.png)

When checked, the script should filter out excluded items at these steps which could potentially pull them in.  Do you have this option checked?

**Comment by ccastillo-id** [comment]
My fault, haha we can close this. Yeah I was searching wrong
